<?php
/*
 * This file adds ACF controlled fields on pages.
 * 
 */

 // support page attributes
// Don't die if ACF isn't installed
if ( function_exists( 'acf_add_local_field_group' ) ) {
    add_action( 'acf/init', 'registerFields' );
}

function registerFields(){

    // ACF Group: Page Details
    acf_add_local_field_group( array (
        'key'      => 'group_page_details',
        'title'    => 'Page Details',
        'location' => array (
            array (
                array (
                    'param'    => 'post_type',
                    'operator' => '==',
                    'value'    => 'page',
                ),
                array (
                    'param'    => 'page_type',
                    'operator' => '!=',
                    'value'    => 'front_page',
                )
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
    ) );

    // Image
    acf_add_local_field( array(
        'key'           => 'header_image',
        'label'         => 'Header Image',
        'name'          => 'header_image',
        'type'          => 'image',
        'parent'        => 'group_page_details',
        'instructions'  => '',
        'required'      => 0,
        'return_format' => 'array',
        'preview_size'  => 'large',
        'library'       => 'all',
        'min_width'     => 0,
        'min_height'    => 0,
        'max_width'     => 0,
        'max_height'    => 0,
    ) );

    // Headline
    acf_add_local_field( array(
        'key'          => 'headline',
        'label'        => 'Headline',
        'name'         => 'headline',
        'type'         => 'text',
        'parent'       => 'group_page_details',
        'instructions' => '',
        'required'     => 0,
    ) );

    register_field_group(array (
		'id' => 'acf_foreclosure',
		'title' => 'Foreclosure',
		'fields' => array (
			array (
				'key' => 'field_54762d77545e5',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'required' => 1,
				'display_format'	=> 'm/d/Y',
			    'return_format'		=> 'm/d/Y',
				'first_day' => 0,
			),
			array (
				'key' => 'field_547631e5a5ad9',
				'label' => 'Case #',
				'name' => 'case_#',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54763208a5ada',
				'label' => 'Plaintiff',
				'name' => 'plaintiff',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54763226a5adb',
				'label' => 'Defendant',
				'name' => 'defendant',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54763244a5adc',
				'label' => 'F/J Amount',
				'name' => 'fj_amount',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_547632c8a5add',
				'label' => 'Book',
				'name' => 'book',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54763379a5ade',
				'label' => 'Page',
				'name' => 'page',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_548b3e4f430db',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'select',
				'instructions' => 'Select active, cancelled or unpublished',
				'required' => 1,
				'choices' => array (
					'active' => 'Active',
					'unpublished' => 'Unpublished',
					'cancelled' => 'Cancelled',
				),
				'default_value' => 'active',
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'foreclosure',
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'slug',
				7 => 'author',
				8 => 'format',
				9 => 'featured_image',
				10 => 'tags',
				11 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_tax-deed-sale',
		'title' => 'Tax Deed Sale',
		'fields' => array (
			array (
				'key' => 'field_547657127682d',
				'label' => 'Date',
				'name' => 'date',
				'type' => 'date_picker',
				'required' => 1,
				'display_format'	=> 'm/d/Y',
			    'return_format'		=> 'm/d/Y',
				'first_day' => 0,
			),
			array (
				'key' => 'field_547651a51c9ee',
				'label' => 'Case #',
				'name' => 'tax_deed',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5476518c1c9ed',
				'label' => 'Certificate #',
				'name' => 'tax_cert',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_547651bd6c75c',
				'label' => 'Parcel ID',
				'name' => 'parcel',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46d6f7b7a7',
				'label' => 'Applicant',
				'name' => 'applicant',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46dc74e371',
				'label' => 'Owner',
				'name' => 'owner',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_548b151cd2d8d',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'select',
				'instructions' => 'Select active, surplus, cancelled, redeemed, closed, rescheduled, or unpublished,',
				'required' => 1,
				'choices' => array (
					'active' => 'Active',
					'unpublished' => 'Unpublished',
					'cancelled' => 'Cancelled',
					'redeemed' => 'Redeemed',
					'surplus' => 'Surplus',
					'closed' => 'Closed',
					'rescheduled' => 'Rescheduled',
				),
				'default_value' => 'active',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_547652ec6c75e',
				'label' => 'Property Address',
				'name' => 'legal_description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'no',
			),
			array (
				'key' => 'field_547651d46c75d',
				'label' => 'Estimated Minimum Bid or Surplus',
				'name' => 'opening_bid',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46df44e372',
				'label' => 'Estimated Minimum Deposit',
				'name' => 'estimated_minimum_deposit',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46e024e373',
				'label' => 'High Bid',
				'name' => 'high_bid',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46e074e374',
				'label' => 'Surplus Funds',
				'name' => 'surplus_funds',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b46e124e375',
				'label' => 'Lands Available',
				'name' => 'lands_available',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58b473c369c1c',
				'label' => 'Owner & Encumbrance Reports',
				'name' => 'owner_&_encumbrance_reports',
				'type' => 'file',
				'save_format' => 'object',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_58f67dff4779f',
				'label' => 'Claim Form',
				'name' => 'claim_form',
				'type' => 'file',
				'save_format' => 'object',
				'library' => 'uploadedTo',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'tax-deed-sale',
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'revisions',
				2 => 'slug',
				3 => 'author',
			),
		),
		'menu_order' => 0,
	));
}
